name: actions
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  # tests:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Use Node.js 23.x
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: "23.x"

  #     - name: Install Dependancies
  #       run: pnpm install

  #     - name: Run Tests
  #       run: pnpm test

  build-deploy:
    runs-on: ubuntu-latest
    if: needs.test.result == 'success' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 23.x
        uses: actions/setup-node@v4
        with:
          node-version: "23.x"

      - name: Install Dependancies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
